package controller;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import application.Main;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.input.MouseEvent;
import model.Category;
import model.Dao;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class CategoryController implements Initializable{
	@FXML
	private Button btnDashboard;
	@FXML
	private Button btnCategory;
	@FXML
	private Button btnProduct;
	@FXML
	private Button btnCustomer;
	@FXML
	private Button btnOrder;
	@FXML
	private Button btnViewOrder;
	@FXML
	private TableView<Category> tCategory;
	@FXML
	private TableColumn<Category, Integer> colId;
	@FXML
	private TableColumn<Category, String> colName;
	@FXML
	private TextField tfName;
	@FXML
	private Button btnAdd;
	@FXML
	private Button btnUpdate;
	@FXML
	private Button btnDelete;
	@FXML
	private Button btnReset;
	@FXML
	private TextField tfId;
	
	private Alert alert;
	
	Main m;
	
	@FXML
    private Button btnLogout;
    
    @FXML
    void onLogoutBtnClick(ActionEvent event) throws IOException {
    	m.changeScene("/view/LoginPage.fxml");

    }

	// Event Listener on Button[#btnDash].onAction
	@FXML
	public void onDashBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m=new Main();
		m.changeScene("/view/Dashboard.fxml");
	}
	// Event Listener on Button[#btnCategory].onAction
	@FXML
	public void onCategoryBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m=new Main();
		m.changeScene("/view/Category.fxml");
	}
	// Event Listener on Button[#btnProduct].onAction
	@FXML
	public void onProductBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m=new Main();
		m.changeScene("/view/Product.fxml");
	}
	// Event Listener on Button[#btnCustomer].onAction
	@FXML
	public void onCustomerBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m=new Main();
		m.changeScene("/view/Customer.fxml");
	}
	// Event Listener on Button[#btnOrder].onAction
	@FXML
	public void onOrderBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m=new Main();
		m.changeScene("/view/Order.fxml");
	}
	// Event Listener on Button[#btnViewOrder].onAction
	@FXML
	public void onViewOrderBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m=new Main();
		m.changeScene("/view/ViewOrder.fxml");
	}
	
	@FXML
    void onAddBtnClick(ActionEvent event) {
		String id= tfId.getText();
		String name = tfName.getText();
		Dao dao = new Dao();
		if(dao.getCategoryById(Integer.valueOf(id))) {
			alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Successful Message");
			alert.setHeaderText(null);
			alert.setContentText("Category is already exists!");
			alert.showAndWait();
		} else {
		boolean result = dao.addCategory(Integer.valueOf(id), name);
		if(result == true) {
			alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Successful Message");
			alert.setHeaderText(null);
			alert.setContentText("Category added successfully!!");
			alert.showAndWait();
			showCategories();
		}
		}

    }

    @FXML
    void onDeleteBtnClick(ActionEvent event) {
    	String id= tfId.getText();
    	Dao dao = new Dao();
		boolean result = dao.deleteCategory(Integer.valueOf(id));
		if(result == true) {
			alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Successful Message");
			alert.setHeaderText(null);
			alert.setContentText("Category Deleted Successfully!!");
			alert.showAndWait();
			showCategories();
		}

    }

    @FXML
    void onResetBtnClick(ActionEvent event) {
    	tfId.setText(null);
    	tfName.setText(null);

    }

    @FXML
    void onUpdateBtnClick(ActionEvent event) {
    	String id= tfId.getText();
		String name = tfName.getText();
		Dao dao = new Dao();
		boolean result = dao.updateCategory(Integer.valueOf(id), name);
		if(result == true) {
			alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Successful Message");
			alert.setHeaderText(null);
			alert.setContentText("Category Updated Successfully!!");
			alert.showAndWait();
			showCategories();
		}

    }
	
	public void showCategories() {
		Dao dao = new Dao();
		ObservableList<Category> list = dao.getCategoryList();
		colId.setCellValueFactory(new PropertyValueFactory<Category, Integer>("id"));
		colName.setCellValueFactory(new PropertyValueFactory<Category, String>("name"));
		tCategory.setItems(list);
	}
	
	
	@Override
    public void initialize(URL url, ResourceBundle rb) {
		showCategories();
	}
	
	@FXML
    void handleOnMouseclick(MouseEvent event) {
		Category category = tCategory.getSelectionModel().getSelectedItem();
		tfId.setText(""+category.getId());
		tfName.setText(category.getName());

    }


}
