package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.cell.PropertyValueFactory;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import application.Main;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.input.MouseEvent;
import model.Customer;
import model.CustomerDao;
import model.Product;
import model.ProductDao;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class CustomerController implements Initializable{
	@FXML
	private Button btnDash;
	@FXML
	private Button btnCategory;
	@FXML
	private Button btnProduct;
	@FXML
	private Button btnCustomer;
	@FXML
	private Button btnOrder;
	@FXML
	private Button btnViewOrder;
	@FXML
	private TableView<Customer> tCustomer;
	@FXML
	private TableColumn<Customer, Integer> colId;
	@FXML
	private TableColumn<Customer, String> colName;
	@FXML
	private TableColumn<Customer, String> colMbl;
	@FXML
	private TableColumn<Customer, String> colEmail;
	@FXML
	private TextField tfName;
	@FXML
	private Button btnAdd;
	@FXML
	private Button btnUpdate;
	@FXML
	private Button btnDelete;
	@FXML
	private Button btnReset;
	@FXML
	private TextField tfId;
	@FXML
	private TextField tfMbl;
	@FXML
	private TextField tfEmail;
	
	Alert alert;
	Main m=new Main();
	
	@FXML
    private Button btnLogout;
    
    @FXML
    void onLogoutBtnClick(ActionEvent event) throws IOException {
    	m.changeScene("/view/LoginPage.fxml");

    }

	// Event Listener on Button[#btnDash].onAction
	@FXML
	public void onDashBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m.changeScene("/view/Dashboard.fxml");
	}
	// Event Listener on Button[#btnCategory].onAction
	@FXML
	public void onCategoryBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m.changeScene("/view/Category.fxml");
	}
	// Event Listener on Button[#btnProduct].onAction
	@FXML
	public void onProductBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m.changeScene("/view/Product.fxml");
	}
	// Event Listener on Button[#btnCustomer].onAction
	@FXML
	public void onCustomerBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m.changeScene("/view/Customer.fxml");
	}
	// Event Listener on Button[#btnOrder].onAction
	@FXML
	public void onOrderBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m.changeScene("/view/Order.fxml");
	}
	// Event Listener on Button[#btnViewOrder].onAction
	@FXML
	public void onViewOrderBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m.changeScene("/view/ViewOrder.fxml");
	}

	// Event Listener on TableView[#tCustomer].onMouseClicked
	@FXML
	public void handleOnMouseclick(MouseEvent event) {
		// TODO Autogenerated
		
		Customer customer=tCustomer.getSelectionModel().getSelectedItem();
		tfId.setText("" + customer.getId());
		tfName.setText(customer.getName());
		tfMbl.setText(customer.getMobile());
		tfEmail.setText(customer.getEmail());
		
	}
	// Event Listener on Button[#btnAdd].onAction
	@FXML
	public void onAddBtnClick(ActionEvent event) {
		// TODO Autogenerated
		String id=tfId.getText();
		String name=tfName.getText();
		String mobile= tfMbl.getText();
		String email=tfEmail.getText();
		CustomerDao dao= new CustomerDao();
		if(dao.getCustomerBtId(Integer.valueOf(id))) {
			alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Successful Message");
			alert.setHeaderText(null);
			alert.setContentText("CustomerId Is Already Exists!!");
			alert.showAndWait();
		} else {
		boolean result = dao.addCustomer(Integer.valueOf(id), name, mobile, email);
		if(result == true) {
			alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Successful Message");
			alert.setHeaderText(null);
			alert.setContentText("Customer Added successfully!!");
			alert.showAndWait();
			showCustomers();
		}
		}
	}
	// Event Listener on Button[#btnUpdate].onAction
	@FXML
	public void onUpdateBtnClick(ActionEvent event) {
		// TODO Autogenerated
		String id=tfId.getText();
		String name=tfName.getText();
		String mobile= tfMbl.getText();
		String email=tfEmail.getText();
		CustomerDao dao= new CustomerDao();
		boolean result = dao.updateCustomer(Integer.valueOf(id), name, mobile, email);
		if(result == true) {
			alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Successful Message");
			alert.setHeaderText(null);
			alert.setContentText("Customer Updated successfully!!");
			alert.showAndWait();
			showCustomers();
		}
	}
	// Event Listener on Button[#btnDelete].onAction
	@FXML
	public void onDeleteBtnClick(ActionEvent event) {
		// TODO Autogenerated
		String id=tfId.getText();
		CustomerDao dao= new CustomerDao();
		boolean result = dao.deleteCustomer(Integer.valueOf(id));
		if(result == true) {
			alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Successful Message");
			alert.setHeaderText(null);
			alert.setContentText("Customer Deleted successfully!!");
			alert.showAndWait();
			showCustomers();
		}
	}
	// Event Listener on Button[#btnReset].onAction
	@FXML
	public void onResetBtnClick(ActionEvent event) {
		// TODO Autogenerated
		tfId.setText(null);
		tfName.setText(null);
		tfMbl.setText(null);
		tfEmail.setText(null);
	}
	@Override
    public void initialize(URL url, ResourceBundle rb) {
		showCustomers();
	}
	public void showCustomers() {
		// TODO Auto-generated method stub
		CustomerDao dao=new CustomerDao();
		ObservableList<Customer> list= dao.getCustomerList();
		System.out.println("list " +list.size());
		colId.setCellValueFactory(new PropertyValueFactory<Customer, Integer>("id"));
		colName.setCellValueFactory(new PropertyValueFactory<Customer, String>("name"));
		colMbl.setCellValueFactory(new PropertyValueFactory<Customer, String>("mobile"));
		colEmail.setCellValueFactory(new PropertyValueFactory<Customer, String>("email"));
		tCustomer.setItems(list);
	}
}
