package controller;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import model.Dao;
import model.User;

import java.io.IOException;

import application.Main;
import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

import javafx.scene.control.Hyperlink;

public class LoginPageController {
	@FXML
	private PasswordField password;
	@FXML
	private TextField username;
	@FXML
	private Hyperlink signup;
	@FXML
	private Button signin;

	Main m=new Main();

	private Alert alert;

	// Event Listener on Hyperlink[#signup].onAction
	@FXML
	public void onSignUpBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m.changeScene("/view/SignUp.fxml");
	}
	// Event Listener on Button[#signin].onAction
	@FXML
	public void onSignInBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated


		String userName = username.getText();
		String pswd = password.getText();
		Dao dao=new Dao();
		if(userName.equals("") || pswd.equals("")) {
			alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Information Message");
			alert.setHeaderText(null);
			alert.setContentText("Username and password are required");
			alert.showAndWait();
		} else {
			User user = dao.getUserByUsername(userName);
			if(user.getUsername().equals(userName) && user.getPassword().equals(pswd)) {
				alert = new Alert(AlertType.INFORMATION);
				alert.setTitle("Successful Message");
				alert.setHeaderText(null);
				alert.setContentText("Login Successfull!");
				System.out.println("Successfully logged in");
				alert.showAndWait();
				m.changeScene("/view/Dashboard.fxml");
			} else {
				alert = new Alert(AlertType.ERROR);
				alert.setTitle("Error Message");
				alert.setHeaderText(null);
				alert.setContentText("Invalid Username or Password");
				alert.showAndWait();
			}
		}
	}
}
