package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.cell.PropertyValueFactory;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import application.Main;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.input.MouseEvent;
import model.Category;
import model.Dao;
import model.Product;
import model.ProductDao;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class ProductController implements Initializable{
	@FXML
	private Button btnDash;
	@FXML
	private Button btnCategory;
	@FXML
	private Button btnProduct;
	@FXML
	private Button btnCustomer;
	@FXML
	private Button btnOrder;
	@FXML
	private Button btnViewOrder;
	@FXML
	private TextField tfName;
	@FXML
	private Button btnAdd;
	@FXML
	private Button btnUpdate;
	@FXML
	private Button btnDelete;
	@FXML
	private Button btnReset;
	@FXML
	private TextField tfQty;
	@FXML
	private TextField tfPrice;
	@FXML
	private TextField tfDesc;
	@FXML
	private ComboBox<String> tfCategories;
	@FXML
	private TableView<Product> tProduct;
	@FXML
	private TableColumn<Product, Integer> colId;
	@FXML
	private TableColumn<Product, String> colName;
	@FXML
	private TableColumn<Product, Integer> colQty;
	@FXML
	private TableColumn<Product, Integer> colPrice;
	@FXML
	private TableColumn<Product, String> colDesc;
	@FXML
	private TableColumn<Product, String> colCategory;
	@FXML
	private TextField tfId;
	
	Alert alert;
	Main m=new Main();
	
	@FXML
    private Button btnLogout;
    
    @FXML
    void onLogoutBtnClick(ActionEvent event) throws IOException {
    	m.changeScene("/view/LoginPage.fxml");
    }

	// Event Listener on Button[#btnDash].onAction
	@FXML
	public void onDashBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m.changeScene("/view/Dashboard.fxml");
	}
	// Event Listener on Button[#btnCategory].onAction
	@FXML
	public void onCategoryBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m.changeScene("/view/Category.fxml");
	}
	// Event Listener on Button[#btnProduct].onAction
	@FXML
	public void onProductBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m.changeScene("/view/Product.fxml");
	}
	// Event Listener on Button[#btnCustomer].onAction
	@FXML
	public void onCustomerBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m.changeScene("/view/Customer.fxml");
	}
	// Event Listener on Button[#btnOrder].onAction
	@FXML
	public void onOrderBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m.changeScene("/view/Order.fxml");
	}
	// Event Listener on Button[#btnViewOrder].onAction
	@FXML
	public void onViewOrderBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m.changeScene("/view/ViewOrder.fxml");
	}

	// Event Listener on Button[#btnAdd].onAction
	@FXML
	public void onAddBtnClick(ActionEvent event) {
		// TODO Autogenerated
		String id=tfId.getText();
		String name=tfName.getText();
		String qty= tfQty.getText();
		String price=tfPrice.getText();
		String desc=tfDesc.getText();
		String category=tfCategories.getSelectionModel().getSelectedItem();
		ProductDao dao= new ProductDao();
		if(dao.getProductById(Integer.valueOf(id))) {
			alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Successful Message");
			alert.setHeaderText(null);
			alert.setContentText("ProductId Is Already Exists!!");
			alert.showAndWait();
		} else {
		boolean result = dao.addProduct(Integer.valueOf(id), name, Integer.valueOf(qty), Integer.valueOf(price), desc, category);
		if(result == true) {
			alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Successful Message");
			alert.setHeaderText(null);
			alert.setContentText("Product Added successfully!!");
			alert.showAndWait();
			showProducts();
		}
		}
	}
	// Event Listener on Button[#btnUpdate].onAction
	@FXML
	public void onUpdateBtnClick(ActionEvent event) {
		// TODO Autogenerated
		String id=tfId.getText();
		String name=tfName.getText();
		String qty= tfQty.getText();
		String price=tfPrice.getText();
		String desc=tfDesc.getText();
		String category=tfCategories.getSelectionModel().getSelectedItem();
		ProductDao dao= new ProductDao();
		boolean result = dao.updateProduct(Integer.valueOf(id), name, Integer.valueOf(qty), Integer.valueOf(price), desc, category);
		if(result == true) {
			alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Successful Message");
			alert.setHeaderText(null);
			alert.setContentText("Product Updated successfully!!");
			alert.showAndWait();
			showProducts();
		}
	}
	// Event Listener on Button[#btnDelete].onAction
	@FXML
	public void onDeleteBtnClick(ActionEvent event) {
		// TODO Autogenerated
		String id=tfId.getText();
		ProductDao dao= new ProductDao();
		boolean result = dao.deleteProduct(Integer.valueOf(id));
		if(result == true) {
			alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Successful Message");
			alert.setHeaderText(null);
			alert.setContentText("Product Deleted successfully!!");
			alert.showAndWait();
			showProducts();
		}
	}
	// Event Listener on Button[#btnReset].onAction
	@FXML
	public void onResetBtnClick(ActionEvent event) {
		// TODO Autogenerated
		tfId.setText(null);
		tfName.setText(null);
		tfQty.setText(null);
		tfPrice.setText(null);
		tfDesc.setText(null);
		ProductDao dao= new ProductDao();
	}
	// Event Listener on TableView[#tProduct].onMouseClicked
	@FXML
	public void handleOnMouseClick(MouseEvent event) {
		// TODO Autogenerated
		Product product = tProduct.getSelectionModel().getSelectedItem();
		tfId.setText("" + product.getId());
		tfName.setText(product.getName());
		tfQty.setText("" + product.getQuantity());
		tfPrice.setText("" + product.getPrice());
		tfDesc.setText("" + product.getDescription());
		tfCategories.setAccessibleText(product.getCategory());
		
	}
	
	public void showProducts() {
		ProductDao dao=new ProductDao();
		ObservableList<Product> list= dao.getProductList();
		colId.setCellValueFactory(new PropertyValueFactory<Product, Integer>("id"));
		colName.setCellValueFactory(new PropertyValueFactory<Product, String>("name"));
		colQty.setCellValueFactory(new PropertyValueFactory<Product, Integer>("quantity"));
		colPrice.setCellValueFactory(new PropertyValueFactory<Product, Integer>("price"));
		colDesc.setCellValueFactory(new PropertyValueFactory<Product, String>("description"));
		colCategory.setCellValueFactory(new PropertyValueFactory<Product, String>("category"));
		tProduct.setItems(list);
	}
	@Override
    public void initialize(URL url, ResourceBundle rb) {
		showProducts();
	}
	 
	 @FXML
	 public void loadCategories(MouseEvent event) {
		 ProductDao dao = new ProductDao();
			ObservableList<String> list = dao.getCategories();
			System.out.println("list " +list.toString());
			tfCategories.setItems(list);
			


	    }
}
