package controller;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import model.Dao;
import model.User;

import java.io.IOException;

import application.Main;
import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

import javafx.scene.control.Hyperlink;

public class SignUpController {
	@FXML
	private TextField username;
	@FXML
	private TextField email;
	@FXML
	private PasswordField password;
	@FXML
	private PasswordField confirmpassword;
	@FXML
	private Hyperlink signin;
	@FXML
	private Button signup;
	
	private Alert alert;
	
	Main m=new Main();

	// Event Listener on Hyperlink[#signin].onAction
	@FXML
	public void onSignInBtnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		m.changeScene("/view/LoginPage.fxml");
	}
	
	@FXML
	public void onSignUpBtnClick(ActionEvent event) throws IOException {
		
		String user = username.getText();
		String pswd = password.getText();
		String mail = email.getText();
		String confirmPswd = confirmpassword.getText();
		
		Dao dao=new Dao();
		
		User userExists = dao.getUserByUsername(user);
		if(user.equals("") || pswd.equals("") || mail.equals("") || confirmPswd.equals(""))
		{
			alert = new Alert(AlertType.ERROR);
			alert.setTitle("Error Message");
			alert.setHeaderText(null);
			alert.setContentText("Please enter the details");
			alert.showAndWait();
			
		}else if(!pswd.equals(confirmPswd))
		{
			alert = new Alert(AlertType.ERROR);
			alert.setTitle("Error Message");
			alert.setHeaderText(null);
			alert.setContentText("Please enter the password correctly");
			alert.showAndWait();
		}
		else if(userExists != null) {
			alert = new Alert(AlertType.ERROR);
			alert.setTitle("Error Message");
			alert.setHeaderText(null);
			alert.setContentText("This Username is already exist");
			alert.showAndWait();
		} else {
		   if(dao.addUser(user, pswd, mail)) {
			   alert = new Alert(AlertType.INFORMATION);
				alert.setTitle("Successful Message");
				alert.setHeaderText(null);
				alert.setContentText("User Added Successfully. Please login!");
				alert.showAndWait();
				m.changeScene("/view/LoginPage.fxml");
		   } else {
			   alert = new Alert(AlertType.ERROR);
				alert.setTitle("Error Message");
				alert.setHeaderText(null);
				alert.setContentText("Could not add user");
				alert.showAndWait();
		   }
		}
	}
}
